### ISSUE TITLE
Update to options to include a GNU/MKL RStudio 

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/bc_osc_rstudio_server_pitzer#1]
The new version uses `R/3.6.0` with `gnu/7.3.0` and `mkl/2018.0.3`.

**Comment by MorganRodgers** [comment]
Related to https://github.com/OSC/bc_osc_rstudio_server/issues/18.

**Comment by ericfranz** [comment]
Would be added as a line to https://github.com/OSC/bc_osc_rstudio_server_pitzer/blob/c11c687fd7ffd652d80a4257dc1c5a368968fc4d/form.yml#L46

```
      - [ "3.6.0", "gnu/7.3.0 mkl/2018.0.3 R/3.6.0 rstudio/1.2.1335"]
```
